version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    restart: unless-stopped
    command: sh -c "npm run dev -- --host 0.0.0.0"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
